//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string birth { get; set; }
        public Nullable<int> role_id { get; set; }
        public Nullable<int> country_id { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> gender_id { get; set; }
        public Nullable<int> direction_id { get; set; }
        public Nullable<int> event_id { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Role Role { get; set; }
    }
}
